# Generated by Django 5.2.4 on 2025-08-22 14:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be in format: '+639123456789' or '09123456789'", regex='^(\\+639\\d{9}|09\\d{9})$')]),
        ),
    ]
