# Generated by Django 5.2.4 on 2025-07-25 15:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIProcessingJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_type', models.CharField(choices=[('categorize_transactions', 'Categorize Transactions'), ('generate_summary', 'Generate Summary'), ('detect_anomalies', 'Detect Anomalies'), ('extract_insights', 'Extract Insights'), ('validate_data', 'Validate Data')], max_length=30)),
                ('input_data', models.JSONField(help_text='Input data for the AI processing job')),
                ('parameters', models.JSONField(default=dict, help_text='Additional parameters for the job')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('progress_percentage', models.PositiveIntegerField(default=0)),
                ('output_data', models.JSONField(blank=True, help_text='Output from the AI processing', null=True)),
                ('error_message', models.TextField(blank=True)),
                ('model_used', models.CharField(blank=True, help_text='AI model used for processing', max_length=100)),
                ('model_version', models.CharField(blank=True, max_length=50)),
                ('processing_time_seconds', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('tokens_used', models.PositiveIntegerField(blank=True, null=True)),
                ('cost_usd', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Processing Job',
                'verbose_name_plural': 'AI Processing Jobs',
                'db_table': 'kitako_ai_processing_jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIModelUsage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('model_name', models.CharField(max_length=100)),
                ('provider', models.CharField(default='openrouter', max_length=50)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('total_tokens', models.PositiveIntegerField(default=0)),
                ('input_cost_per_token', models.DecimalField(decimal_places=8, default=0, max_digits=12)),
                ('output_cost_per_token', models.DecimalField(decimal_places=8, default=0, max_digits=12)),
                ('total_cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('response_time_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_usage', to=settings.AUTH_USER_MODEL)),
                ('processing_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usage_records', to='ai_processing.aiprocessingjob')),
            ],
            options={
                'verbose_name': 'AI Model Usage',
                'verbose_name_plural': 'AI Model Usage Records',
                'db_table': 'kitako_ai_model_usage',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIPromptTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('task_type', models.CharField(choices=[('transaction_categorization', 'Transaction Categorization'), ('income_summary', 'Income Summary'), ('expense_analysis', 'Expense Analysis'), ('anomaly_detection', 'Anomaly Detection'), ('insight_generation', 'Insight Generation'), ('data_validation', 'Data Validation')], max_length=30)),
                ('system_prompt', models.TextField(help_text='System prompt for the AI model')),
                ('user_prompt_template', models.TextField(help_text='User prompt template with placeholders like {transaction_data}')),
                ('model_name', models.CharField(default='claude-3-sonnet', max_length=100)),
                ('temperature', models.DecimalField(decimal_places=2, default=0.1, max_digits=3)),
                ('max_tokens', models.PositiveIntegerField(default=4000)),
                ('expected_output_format', models.TextField(blank=True, help_text='Description of expected output format')),
                ('validation_schema', models.JSONField(blank=True, help_text='JSON schema for validating AI output', null=True)),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('success_rate', models.DecimalField(decimal_places=2, default=0.0, help_text='Success rate percentage', max_digits=5)),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AI Prompt Template',
                'verbose_name_plural': 'AI Prompt Templates',
                'db_table': 'kitako_ai_prompt_templates',
                'ordering': ['-created_at'],
                'unique_together': {('task_type', 'version', 'is_active')},
            },
        ),
        migrations.AddIndex(
            model_name='aiprocessingjob',
            index=models.Index(fields=['user', 'status'], name='kitako_ai_p_user_id_e82cd8_idx'),
        ),
        migrations.AddIndex(
            model_name='aiprocessingjob',
            index=models.Index(fields=['job_type', 'status'], name='kitako_ai_p_job_typ_e41e24_idx'),
        ),
        migrations.AddIndex(
            model_name='aimodelusage',
            index=models.Index(fields=['user', 'created_at'], name='kitako_ai_m_user_id_c73702_idx'),
        ),
        migrations.AddIndex(
            model_name='aimodelusage',
            index=models.Index(fields=['model_name'], name='kitako_ai_m_model_n_2e2926_idx'),
        ),
    ]
