# Generated by Django 5.2.4 on 2025-07-25 15:51

import django.core.validators
import django.db.models.deletion
import reports.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomeReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_type', models.CharField(choices=[('monthly', 'Monthly Report'), ('quarterly', 'Quarterly Report'), ('annual', 'Annual Report'), ('custom', 'Custom Date Range')], max_length=20)),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('purpose', models.CharField(choices=[('loan_application', 'Loan Application'), ('government_subsidy', 'Government Subsidy'), ('insurance_application', 'Insurance Application'), ('rental_application', 'Rental Application'), ('business_registration', 'Business Registration'), ('visa_application', 'Visa Application'), ('other', 'Other')], max_length=30)),
                ('purpose_description', models.TextField(blank=True)),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField(help_text='AI-generated summary of financial activity')),
                ('total_income', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_expenses', models.DecimalField(decimal_places=2, max_digits=12)),
                ('net_income', models.DecimalField(decimal_places=2, max_digits=12)),
                ('average_monthly_income', models.DecimalField(decimal_places=2, max_digits=12)),
                ('income_breakdown', models.JSONField(default=dict, help_text='Breakdown of income by category')),
                ('expense_breakdown', models.JSONField(default=dict, help_text='Breakdown of expenses by category')),
                ('monthly_trends', models.JSONField(default=dict, help_text='Monthly income/expense trends')),
                ('data_sources', models.JSONField(default=list, help_text='List of data sources used (e.g., GCash, BPI, etc.)')),
                ('transaction_count', models.PositiveIntegerField(default=0)),
                ('ai_insights', models.TextField(blank=True, help_text='AI-generated insights and patterns')),
                ('anomalies_detected', models.JSONField(default=list, help_text='List of anomalies detected in the data')),
                ('confidence_score', models.DecimalField(decimal_places=2, help_text='Overall confidence score of the report (0-100)', max_digits=5)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to=reports.models.upload_to_reports, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('file_size', models.PositiveIntegerField(blank=True, null=True)),
                ('document_hash', models.CharField(blank=True, help_text='SHA-256 hash for verification', max_length=64)),
                ('verification_code', models.CharField(blank=True, max_length=20, unique=True)),
                ('status', models.CharField(choices=[('generating', 'Generating'), ('completed', 'Completed'), ('failed', 'Failed'), ('expired', 'Expired')], default='generating', max_length=20)),
                ('generation_error', models.TextField(blank=True)),
                ('is_public', models.BooleanField(default=False)),
                ('access_token', models.CharField(blank=True, max_length=64, unique=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='income_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Income Report',
                'verbose_name_plural': 'Income Reports',
                'db_table': 'kitako_income_reports',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='kitako_inco_user_id_7fda0e_idx'), models.Index(fields=['verification_code'], name='kitako_inco_verific_e50e81_idx'), models.Index(fields=['access_token'], name='kitako_inco_access__2bcf08_idx')],
            },
        ),
    ]
