# Generated by Django 5.2.5 on 2025-08-25 01:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='incomereport',
            name='admin_notes',
            field=models.TextField(blank=True, help_text='Admin notes on verification decision'),
        ),
        migrations.AddField(
            model_name='incomereport',
            name='is_signature_submitted',
            field=models.BooleanField(default=False, help_text='Whether user submitted document for signature verification'),
        ),
        migrations.AddField(
            model_name='incomereport',
            name='qr_code_url',
            field=models.URLField(blank=True, help_text='URL that QR code points to for verification'),
        ),
        migrations.AddField(
            model_name='incomereport',
            name='signature_approved_at',
            field=models.DateTimeField(blank=True, help_text='When admin approved/rejected', null=True),
        ),
        migrations.AddField(
            model_name='incomereport',
            name='signature_approved_by',
            field=models.ForeignKey(blank=True, help_text='Admin who approved/rejected the signature', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incomereport',
            name='signature_submitted_at',
            field=models.DateTimeField(blank=True, help_text='When user submitted for verification', null=True),
        ),
        migrations.AddField(
            model_name='incomereport',
            name='signature_verification_status',
            field=models.CharField(choices=[('pending', 'Pending Admin Approval'), ('approved', 'Approved & Verified'), ('rejected', 'Rejected'), ('not_submitted', 'Not Submitted for Verification')], default='not_submitted', help_text='Admin approval status for document signature', max_length=20),
        ),
        migrations.AddIndex(
            model_name='incomereport',
            index=models.Index(fields=['signature_verification_status'], name='kitako_inco_signatu_249967_idx'),
        ),
        migrations.AddIndex(
            model_name='incomereport',
            index=models.Index(fields=['is_signature_submitted'], name='kitako_inco_is_sign_29c250_idx'),
        ),
    ]
