# Generated by Django 5.2.5 on 2025-08-25 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_incomereport_admin_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomereport',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('generating', 'Generating'), ('completed', 'Completed'), ('failed', 'Failed'), ('expired', 'Expired')], default='draft', max_length=20),
        ),
    ]
