# Generated by Django migration for updating existing reports

from django.db import migrations


def update_generating_reports_to_draft(apps, schema_editor):
    """
    Update existing reports with 'generating' status and no PDF file to 'draft' status
    """
    IncomeReport = apps.get_model('reports', 'IncomeReport')
    
    # Update reports that are in 'generating' status but have no PDF file
    # These should be draft reports waiting for PDF generation
    updated_count = IncomeReport.objects.filter(
        status='generating',
        pdf_file__isnull=True
    ).update(status='draft')
    
    print(f"Updated {updated_count} reports from 'generating' to 'draft' status")


def reverse_update_reports(apps, schema_editor):
    """
    Reverse the migration by updating 'draft' status back to 'generating'
    """
    IncomeReport = apps.get_model('reports', 'IncomeReport')
    
    # Reverse the change - update draft reports back to generating
    updated_count = IncomeReport.objects.filter(
        status='draft',
        pdf_file__isnull=True
    ).update(status='generating')
    
    print(f"Reverted {updated_count} reports from 'draft' to 'generating' status")


class Migration(migrations.Migration):
    
    dependencies = [
        ('reports', '0003_alter_incomereport_status'),
    ]
    
    operations = [
        migrations.RunPython(
            update_generating_reports_to_draft,
            reverse_update_reports,
        ),
    ]
