# Generated by Django 5.2.4 on 2025-08-22 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='processing_status',
            field=models.CharField(choices=[('uploaded', 'Uploaded'), ('processing', 'Processing'), ('awaiting_review', 'Awaiting Review'), ('processed', 'Processed'), ('failed', 'Failed'), ('error', 'Error')], default='uploaded', max_length=20),
        ),
    ]
